services:
  db:
    image: postgres:16.1
    container_name: db
    env_file:
      - .env
    user: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./fixtures/init.sql:/docker-entrypoint-initdb.d/init.sql
      - testingservice-pg:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      testingservice-network:

  app:
    build:
      context: .
    restart: always
    env_file:
      - .env
    container_name: testingservice_app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db
    command: bash -c "while !</dev/tcp/db/5432; do sleep 1; done; sleep 2; alembic upgrade head && uvicorn main:app --host ${APP_HOST} --port ${APP_PORT}"
    healthcheck:
      test: bash -c "</dev/tcp/app/${APP_PORT}"
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      testingservice-network:

volumes:
  testingservice-pg:

networks:
  testingservice-network:
    name: testingservice-network