"""create answes, right_answer, question tables

Revision ID: 342feb0c0770
Revises: 73661668a0ce
Create Date: 2024-05-30 13:21:55.449104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '342feb0c0770'
down_revision: Union[str, None] = '73661668a0ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('min_score', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('count_answers', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer1', sa.String(), nullable=False),
    sa.Column('answer2', sa.String(), nullable=False),
    sa.Column('answer3', sa.String(), nullable=True),
    sa.Column('answer4', sa.String(), nullable=True),
    sa.Column('answer5', sa.String(), nullable=True),
    sa.Column('answer6', sa.String(), nullable=True),
    sa.Column('answer7', sa.String(), nullable=True),
    sa.Column('answer8', sa.String(), nullable=True),
    sa.Column('answer9', sa.String(), nullable=True),
    sa.Column('answer10', sa.String(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('right_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer1', sa.String(), nullable=False),
    sa.Column('answer2', sa.String(), nullable=False),
    sa.Column('answer3', sa.String(), nullable=True),
    sa.Column('answer4', sa.String(), nullable=True),
    sa.Column('answer5', sa.String(), nullable=True),
    sa.Column('answer6', sa.String(), nullable=True),
    sa.Column('answer7', sa.String(), nullable=True),
    sa.Column('answer8', sa.String(), nullable=True),
    sa.Column('answer9', sa.String(), nullable=True),
    sa.Column('answer10', sa.String(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('right_answer')
    op.drop_table('answer')
    op.drop_table('question')
    # ### end Alembic commands ###
