"""set 1 or more rightanswers

Revision ID: 8f78f1c1ebc2
Revises: 342feb0c0770
Create Date: 2024-05-31 10:24:02.962759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f78f1c1ebc2'
down_revision: Union[str, None] = '342feb0c0770'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('right_answer', 'answer2',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('right_answer', 'answer2',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
