"""test nullable true scores

Revision ID: c727ab87b879
Revises: 7389vjsefjs
Create Date: 2024-05-31 17:34:35.047885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c727ab87b879'
down_revision: Union[str, None] = '7389vjsefjs'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('question', sa.String(), nullable=False))
    op.add_column('question', sa.Column('min_score', sa.Integer(), nullable=False))
    op.add_column('question', sa.Column('max_score', sa.Integer(), nullable=False))
    op.add_column('question', sa.Column('count_answers', sa.Integer(), nullable=False))
    op.alter_column('question', 'test_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'question', 'test', ['test_id'], ['id'])
    op.drop_column('question', 'content')
    op.alter_column('test', 'min_score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('test', 'max_score',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test', 'max_score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('test', 'min_score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('question', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.alter_column('question', 'test_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('question', 'count_answers')
    op.drop_column('question', 'max_score')
    op.drop_column('question', 'min_score')
    op.drop_column('question', 'question')
    # ### end Alembic commands ###
